### ISSUE TITLE
Cannot Dynamic Endpoint with APIC 2.1 (1h)

### ISSUE THREAD

**Issue by pavaritSCM** [F5Networks/f5-application-services-integration-iApp#15]
## Description
We used appsvcs_integration_v2.0-002_001.tmpl with BIG-IP 11.6.1, iWorkFlow 2.0.2 and APIC 2.1 (1h). We create service graph and enable 'Attachment Notificationand' enter a single pool member with ip address '0.0.0.0'. We plug node(Server) to APIC and APIC detect the node(Server) but not auto create pool member on BIG-IP (dynamic endpoint). We don't know it BUG or not.

## Template
appsvcs_integration_v2.0-002_001.tmpl

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.
Severity: 5

**Comment by RafalKorepta** [comment]
We acknowledged the problem and we are working on it.

**Comment by pavaritSCM** [comment]
How to donwload v2.0.003 ?

**Comment by RafalKorepta** [comment]
You could download it [here](https://github.com/F5Networks/f5-application-services-integration-iApp/releases/download/v2.0.003/appsvcs_integration_v2.0.003.tmpl)
