### ISSUE TITLE
13.0 BIG-IP unable to reconfigure iApp

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-application-services-integration-iApp#16]
## Description
I have a new 13.0 VE running. I understand the appsvc iApp currently maxes support at 12.1.1. I like to be on the edge though. I deploy a simple config, submit, and it is successful. I hit reconfigure, simply try to add another pool member, hit submit, and I get an error saying the requested virtual server was not found.

script did not successfully complete: (01020036:3: The requested Virtual Server (/Common/test1.app) was not found.
while executing
"tmsh::get_config ltm virtual $::app_path/$vsname all-properties"
(procedure "handle_opt_remove_on_redeploy" line 13)
invoked from within
"handle_opt_remove_on_redeploy vs__ProfileSecurityIPBlacklist "none" "ip-intelligence-policy" "ltm"" line:2295)

## Template
Current supported release of appsvc here...
https://github.com/F5Networks/f5-application-services-integration-iApp

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 2

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by RafalKorepta** [comment]
We acknowledged the problem and we are working on it.

**Comment by colin-stubbs** [comment]
Also does not work on v13.1

**Comment by delgadillo22** [comment]
Will not be addressed in AS2, we recommend moving to AS3:
https://github.com/F5Networks/f5-appsvcs-extension

**Comment by JosephPJordan** [comment]
Closed, we recommend moving to AS3: https://github.com/F5Networks/f5-appsvcs-extension
