### ISSUE TITLE
Old Virtual Address object not deleted if address is changed

### ISSUE THREAD

**Issue by phenetrik** [F5Networks/f5-application-services-integration-iApp#20]
## Description
If you reconfigure the Application Service and change the Virtual Server IP address, the old virtual address object is not deleted (no other Virtual Servers are referencing the object)

## Template
f5-application-services-integration-iApp 2.0.002

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

**Comment by RafalKorepta** [comment]
We acknowledged the problem and we are working on it.

**Comment by delgadillo22** [comment]
Will not be addressed in AS2, we recommend moving to AS3:
https://github.com/F5Networks/f5-appsvcs-extension

**Comment by JosephPJordan** [comment]
Closed, we recommend moving to AS3: https://github.com/F5Networks/f5-appsvcs-extension
