### ISSUE TITLE
Parsing error on AdvOptions pool entity when deploying with REST API

### ISSUE THREAD

**Issue by phenetrik** [F5Networks/f5-application-services-integration-iApp#21]
## Description
If the AdvOptions pool entity is left as default (empty string) the iApp throws the following error when deploying via REST 

{
  "code": 400,
  "message": "Invalid table, the number of row elements does not match the number of column headers in table ::pool__Pools in application /PARTITION/APPNAME.app/APPNAME",
  "errorStack": [],
  "apiError": 3
}

Inserting a character such as a space works around the issue

## Template
f5-application-services-integration-iApp 2.0.002

## Severity Level
Severity: 5

**Comment by RafalKorepta** [comment]
We acknowledged the problem and we are working on it.

**Comment by delgadillo22** [comment]
Will not be addressed in AS2, we recommend moving to AS3:
https://github.com/F5Networks/f5-appsvcs-extension

**Comment by JosephPJordan** [comment]
Closing, we recommend moving to AS3: https://github.com/F5Networks/f5-appsvcs-extension
