### ISSUE TITLE
Selecting the template results in MCP error

### ISSUE THREAD

**Issue by vsnine** [F5Networks/f5-application-services-integration-iApp#22]
I built appsvcs_integration_v2.0.003 today from a fresh clone of the repo under Python 2.7. After import, and during deploy, when I select the template via the WebUI on my BIG-IP under version 12.1.2 0.0.249, I get the following error:

Error parsing template:MCP call 'mcpmsg_set_string_item(msg, CID2TAG(m_cid), val.c_str())' failed with error: 16908375, 01020057:3: The string with more than 65535 characters cannot be stored in a message.

/var/log/scriptd.out is empty. Not sure where else to start here.

(edited for clarity)

**Comment by RafalKorepta** [comment]
We acknowledged the problem and we are working on it.

**Comment by RafalKorepta** [comment]
It is resolved by #37
