### ISSUE TITLE
Error in deploying the iApp when AFM is provisioned

### ISSUE THREAD

**Issue by payalsin** [F5Networks/f5-application-services-integration-iApp#24]
## Description

AFM is provisioned on the BIG-IP
Deploying the iApp results in the following error:
----------------------------------------------------------------------------
script did not successfully complete: ("firewall" unexpected argument
while executing
"tmsh::create $feature_easyL4Firewall_blacklistcmd"
invoked from within
"if { $feature__easyL4Firewall == "enabled" } {
debug [list virtual_server l4_firewall] "creating FW policy" 5

set cidr_blacklist [single_column_t..." line:2298)
---------------------------------------------------------------------------

No special parameters specified, using the default AFM parameters specified in the iApp.

**Comment by RafalKorepta** [comment]
We acknowledged the problem and we are working on it.

**Comment by rabru** [comment]
Interesting, after provisioning AVR the issue was gone.

Details:
I got a v12.1.2 HF1 VE installation with LTM, ASM and AFM “Nominal” in provisioning and was facing this issue. After I add AVR as well with “Nominal” into provisioning, it was gone.

**Comment by delgadillo22** [comment]
Will not be addressed in AS2, we recommend moving to AS3:
https://github.com/F5Networks/f5-appsvcs-extension

**Comment by JosephPJordan** [comment]
Closing, we recommend moving to AS3: https://github.com/F5Networks/f5-appsvcs-extension
