### ISSUE TITLE
Not able to configure profiles options with "sub-options" through the Template

### ISSUE THREAD

**Issue by correiap** [F5Networks/f5-application-services-integration-iApp#42]
## Description
Trying to create a custom profile through the App Services iApp, but not able to figure out the syntax for "sub-options"

Example profile to create:
_ltm profile http profile-http-secure {
    app-service none
    defaults-from http
    **enforcement {
        unknown-method allow
    }**
    header-insert Original-Protocol:HTTPS
    proxy-type reverse
}_

In particular:    
**enforcement {
        unknown-method allow
  }**

As per: https://devcentral.f5.com/wiki/iApp.AppSvcsiApp_userguide_module2_lab5.ashx

To create a custom profile, we can use the following syntax: create:type=<profile type>;<tmsh_option_name>=<tmsh_option_value>[;<tmsh_option_name>=<tmsh_option_value>]

However, it wasn’t working for an option that has a “sub-option” associated with it.

Any pointers?

## Template
v2.0.004

## Severity Level
Severity: 4

**Comment by 0xHiteshPatel** [comment]
Looking into this.  The current code to validate profile options does not account for tmsh property groups.  Furthermore the resulting syntax would be fairly messy if the current format is used.

**Comment by correiap** [comment]
Hi @0xHiteshPatel, thanks for checking it.

Any time-frame for implementing this?

Thanks,

Pedro

**Comment by delgadillo22** [comment]
Will not be addressed in AS2, we recommend moving to AS3:
https://github.com/F5Networks/f5-appsvcs-extension

**Comment by JosephPJordan** [comment]
Closing, we recommend moving to AS3: https://github.com/F5Networks/f5-appsvcs-extension
