### ISSUE TITLE
iApp Properties Description overwritten by default

### ISSUE THREAD

**Issue by ryan-talley** [F5Networks/f5-application-services-integration-iApp#43]
## Description
In the iApps->Application Services->Properties GUI the Description field is overwritten by the template by default see: implementation_layer.tcl lines: 102-104. This is causing issues with the F5 BIG-IP controllers which are expecting the description that was originally supplied.

## Template
f5-application-services-integration-iApp v2.0.00x

## Severity Level
Severity: 5

**Comment by 0xHiteshPatel** [comment]
Looking into how we can safely address this without breaking backwards compatibility.  We have some other field that also exhibit this behaviour.  The description field not a huge concern, however, some other fields could cause some breakage.

**Comment by ryan-talley** [comment]
Thank you for looking into this!

**Comment by delgadillo22** [comment]
This issue will not be addressed in AS2, we recommend moving to AS3:
https://github.com/F5Networks/f5-appsvcs-extension

**Comment by JosephPJordan** [comment]
Closing, we recommend moving to AS3: https://github.com/F5Networks/f5-appsvcs-extension
