### ISSUE TITLE
Missing vs__Name while iApp is creating

### ISSUE THREAD

**Issue by RafalKorepta** [F5Networks/f5-application-services-integration-iApp#46]
## Description
There is possibility to send REST request to create iApp and omit vs__Name filed.
In this case postdeploy_final script will crash with error:
script did not successfully complete: (01020036:3: The requested application instance value (/Common/XXX.app/XXX) was not found.
    while executing
"tmsh::modify sys application service /Common/XXX.app/XXX variables modify \{ vs__Name \{ value \"YYY\" \} \}" line:24)

**Comment by delgadillo22** [comment]
Will not be addressed in AS2, we recommend moving to AS3:
https://github.com/F5Networks/f5-appsvcs-extension

**Comment by JosephPJordan** [comment]
Closing, we recommend moving to AS3: https://github.com/F5Networks/f5-appsvcs-extension
