### ISSUE TITLE
Scheduled reconfigure action option

### ISSUE THREAD

**Issue by xdauphin** [F5Networks/f5-application-services-integration-iApp#49]
## Description

IHAC who needs to schedule the iApp reconfigure action. Although this could be done by an orchestrator, the idea is to make the iApp reconfiguration independent, scheduled, and fully integrated in the iApp itself. I believe an iCall could easily do that for example. The goal is to make the iApp able to automatically get the new versions of iRules or ASM policies loaded via URL.
This new feature should introduce a new input variable which is the reconfigure period. For instance, it could accept the following values:
None -> no iCall creation, no scheduled reconfiguration
xD -> an iCall will be created to refresh the config every x day
xH -> an iCall will be created to refresh the config every x hour
xM-> an iCall will be created to refresh the config every x minute
xS -> an iCall will be created to refresh the config every x second

**Comment by delgadillo22** [comment]
Will not be addressed in AS2, we recommend moving to AS3:
https://github.com/F5Networks/f5-appsvcs-extension

**Comment by JosephPJordan** [comment]
Closing, we recommend moving to AS3: https://github.com/F5Networks/f5-appsvcs-extension
