### ISSUE TITLE
Multiple client ssl profiles to manage SNI use cases

### ISSUE THREAD

**Issue by xdauphin** [F5Networks/f5-application-services-integration-iApp#52]
## Description
IHAC who needs to do virtual hosting on his SSL services, so he needs to attach multiple client ssl profiles to a VS and the right one will be dynamically selected by the SNI feature. Currently, this is not feasible in the iApp. Can this common use case be taken into account for a future release?

**Comment by delgadillo22** [comment]
Will not be addressed in AS2, we recommend moving to AS3:
https://github.com/F5Networks/f5-appsvcs-extension

**Comment by JosephPJordan** [comment]
Closing, we recommend moving to AS3: https://github.com/F5Networks/f5-appsvcs-extension
