### ISSUE TITLE
'=' character not properly escaped on Monitor AdvOptions field

### ISSUE THREAD

**Issue by 0xHiteshPatel** [F5Networks/f5-application-services-integration-iApp#6]
## Description
Sending 'send=GET /check?op=ping HTTP/1.0\r\n' for monitor AdvOptions string results in incorrect config being deployed. The second '=' is not escaped properly.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 4

**Comment by 0xHiteshPatel** [comment]
Moving issue over from old repo:
https://github.com/0xHiteshPatel/appsvcs_integration_iapp/issues/31

**Comment by 0xHiteshPatel** [comment]
###Workaround

webify the character... %3D works in lieu of '='

**Comment by delgadillo22** [comment]
Will not be addressed in AS2, we recommend moving to AS3:
https://github.com/F5Networks/f5-appsvcs-extension

**Comment by JosephPJordan** [comment]
Closed, we recommend moving to AS3: https://github.com/F5Networks/f5-appsvcs-extension
